[package]
name = "xsync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh2 = "0.9.3"
adler = "1.0.2"
glob = "0.3.0"
toml = "0.5.8"
serde = { version = "1.0.125", features = ["derive"] }